Feature/api endpoint
vibraneur-capstone/vape-sensor-inventory pull request #12
Opened 2020-01-26 22:04 UTC by Summer0410

Implemented basic api endpoint, which enables front end to query data from the mongodb database.

2020-01-27 00:34 UTC, BenxinNiu requested changes

2020-01-27 00:34 UTC, BenxinNiu commented on src/app.py
> +    app.run(port=8822, debug = True)
pls remove `debug` flag

2020-01-27 00:35 UTC, BenxinNiu commented on src/controllers/sensor_info_controller.py
> +    return json.loads(sensors.to_json())
note for future improvement, nothing major: extract query logic to methods in a different package to improve code readability

2020-01-27 00:35 UTC, BenxinNiu commented
also, conflict with dev branch

2020-01-28 03:34 UTC, Summer0410 commented
Made changes to the pr, @NoahGallant-MUN  I tried to append object count at the end, did not get it working, but the return result is pretty much what you wanted other than the sensor count.  If anyone knows how to add the count at the end, please go ahead.

2020-01-28 15:06 UTC, BenxinNiu approved these changes

2020-01-28 15:07 UTC, BenxinNiu commented
merged with a flag for implementing mapper between Mongo Document and Swagger object (I'll implement this).

2020-01-28 15:07 UTC, merged