Feature/api implementation
vibraneur-capstone/vape-sensor-inventory pull request #18
Opened 2020-02-06 19:20 UTC by Summer0410

Added "Create new bearing" and "Add sensor id to bearing" 2 endpoint. Please checkout the swagger file. If everything is ok, please approve the pr but do not merge the branch to develop since I will need to implement the controllers.

2020-02-06 20:04 UTC, BenxinNiu commented on src/controllers/bearing_info_controller.py
> +
just a side note, the function name should be the same as defined in the swagger. otherwise, endpoints won't be mapped correctly.

2020-02-06 20:07 UTC, BenxinNiu requested changes
Looks good! very restful. please go ahead. (Note: this is NOT a `Request changes`, but just to prevent other merging this branch without ur implementation)

2020-02-07 00:31 UTC, Summer0410 commented
Updated controllers, please review the code.

2020-02-08 17:46 UTC, BenxinNiu approved these changes

2020-02-08 17:46 UTC, merged